### ISSUE TITLE
【Bug】Grafana連携時にメッセージが無限に登録されてしまう

### ISSUE THREAD

**Issue by wreathvine** [exastro-suite/oase#1753]
# 概要
Grafana連携時に同一メッセージが無限に登録されてしまう。

▼設定内容
![image](https://user-images.githubusercontent.com/83527822/151978797-b1e02dc3-950c-4c7b-baf4-c6567e52b515.png)

▼メッセージ
![image](https://user-images.githubusercontent.com/83527822/151978963-a7c6b672-8425-45ac-8885-fd5a5cb7d70c.png)

**Comment by takeo-e** [comment]
ルールファイルが適用されていないことによる、エラーによるリクエストエラーが表示されています。
この動作自体は仕様となります。
